- .circleci/config.yml
- README.md
- package-lock.json
- package.json
- src/connection.ts
- src/protocol.ts
- src/stream.ts
- src/util/data-offset-sorter.ts
- src/util/data-queue.ts
- test/connection.test.ts
- test/stream.test.ts
Frames are sent over the wire to communicate how much data each stream and the connection as a whole can handle. If the other side does not respect the flow control limits we destroy the connection with an error.
Right now, each stream uses the same default highWaterMark as regular Node streams, which is 16kb.
The connection will accept 64kb, which is the equivalent of 2 full ILP packets.
What do you think about these limits?
Resolves https://github.com/interledgerjs/ilp-protocol-stream/issues/7
> Add stream- and connection-level flow control

- src/connection.ts
- test/stream.test.ts
Cleans up logic on when to stop the sending loop. Only makes the sending flag as true if there are still Money, Data, or Close frames present which need to be resent. 
Adds support to retry rejected StreamClose Frames.
> feat: resend closed frames on rejection

- src/connection.ts
- test/connection.test.ts
- Brings in the Retry delay logic 
- Resolves the reduce to 0 and NaN exchange rate errrors
- Increases the packet amount after T04 errors stop so we are not stuck at a low packet amount indefinitely of 2.
> Tc stream fixes

- src/connection.ts
- src/index.ts
- test/connection.test.ts
Add back the logic to increase the retry time for T04 errors.
Add error message to indicate the issue originates from the ilp-protocol-stream module.
> fix: add retry back off for T04 errors

- package-lock.json
- package.json
- src/connection.ts
- test/connection.test.ts
- test/index.test.ts
- test/mocks/plugin.ts
Sends multiple packets at once (1-10^9) to determine the exchange rate
Open question is how it should handle temporary errors (T04s and others) that it gets while sending the initial test packets.
Resolves https://github.com/interledgerjs/ilp-protocol-stream/issues/34
> Support exchange rates with large scale differences

- src/connection.ts
- test/connection.test.ts
Replaces PR #47 default the min precision to 3 digits. 
Only check the prepare amount as discussed in #48 
Update F08 retry logic to support different F08 max packet amounts / allows different updated retry logic for future changes.
> feat: support minExchangeRatePrecision

- src/connection.ts
- src/stream.ts
- test/stream.test.ts
Previously, if the reader stream was in paused mode (i.e. calling `read()`, no `"data"` events) it could get stuck by never notifying the peer that the data was read.
Fixed by:
- reader should send a `StreamMaxData` frame during `loadAndSendPacket`, not just on packet responses.
- Start a send loop during `read()` when paused.
-------
I wasn't able to write a test case that caught this, but the bug is:
When the offset passed at https://github.com/interledgerjs/ilp-protocol-stream/blob/26cdd2c8530035af417f9a7d2ace842f3dc2c321/src/connection.ts#L890 is negative, and there is a chunk in the retry queue, the `size` parameter will be used to slice the data buffer -- which actually takes data from the end of the buffer.
> data read/write fixes

- src/index.ts
- test/index.test.ts
Allow '~' as a character for connection tags. It is a valid ilp address
character, and functions as a delimeter to be able to include more 
than one tag.
> feat: multiple connection tags

- package-lock.json
- package.json
Update to new ilp-logger version which does not include the source map files which will reduce the size of stream by ~100kb when webpacked.
> chore: update ilp-logger to 1.1.3

- package-lock.json
- package.json
- src/connection.ts
- src/packet.ts
- test/benchmarks/packet.ts
Depends on https://github.com/interledgerjs/oer-utils/pull/21.
Benchmarks (before and after):
```
serialize:   MoneyFrame          v0 x 25,560 ops/sec ±0.84% (93 runs sampled)
serialize:   MoneyFrame          v1 x 116,407 ops/sec ±1.60% (95 runs sampled)
deserialize: MoneyFrame          v0 x 114,379 ops/sec ±2.44% (89 runs sampled)
deserialize: MoneyFrame          v1 x 206,280 ops/sec ±0.55% (90 runs sampled)
```
Also includes misc fix: clean up the idle timer when a connection closes.
> perf: use oer-utils#dj-alloc-writer

- package-lock.json
- src/connection.ts
- test/connection.test.ts
**Problem**: The default slippage is 0 in STREAM. In a practical setting a path of connectors involves multiple currencies, the rate backends of the connectors round floats, and different connectors might pull rates from different exchanges/sources. Thus a slippage of 0 rarely works.
**Proposed Solution**: There are other parameters that seem to be pragmatic defaults (like allowableReceiveExtra being at 1.01). Slippage being at 0.01 is practical.
**Downside**: The sender might lose up to 1% of a payment depending on exchange rate volatility if they don't manually configure slippage in their STREAM server/client.
Thoughts?
> fix: default slippage

- package-lock.json
- package.json
- src/connection.ts
- src/util/congestion.ts
- src/util/rational.ts
- test/connection.test.ts
* Add `ConnectionOpts.maximumPacketAmount` option.
* Add `ConnectionOpts.exchangeRate` option. When set, the rate volley is skipped and this fixed rate is used instead.
* Drop the stream connection after too many packets sent (`2^31`).
* Update typedoc. Hopefully this will fix the `publish_docs` circleci task.
* Some refactoring of congestion control.
> skip volley

- package-lock.json
- package.json
- src/connection.ts
- src/index.ts
- test/connection.test.ts
Depends on the ilp-protocol-ildcp change at https://github.com/interledgerjs/interledgerjs/pull/7 (CI will fail until that is updated).
This option is useful in the web extension when the client has a badly skewed clock. The extension can set a fixed, distant `expiresAt` for all Prepare packets. The first connector will automatically [replace it with a sensible value](https://github.com/interledgerjs/ilp-connector/blob/ff20aff6f064945ef4b616baaa06990c2592707a/src/services/route-builder.ts#L122) (`now + maxHoldTime`).
> feat: add getExpiry option to createConnection

- package-lock.json
- package.json
- src/connection.ts
- src/stream.ts
Currently debugging logs from STREAM is very difficult when trying to identify logs for a particular STREAM and Connection. This adds a uuid to the connection logging as well as the DataAndMoneyStream. This should allow someone debugging to filter the logs for a particular connection and see its lifecycle easier. Especially Streams in server mode
> chore: Better logging

- src/connection.ts
- test/connection.test.ts
It can be useful to have access to the ILP rejection instead of just string a description of it.
> feat: attach rejection to error

- package-lock.json
- package.json
Updates documentation to use https://github.com/google/typedoc-neo-theme which are a little more readable. 
You can look at https://interledgerjs.github.io/ilp-protocol-stream/classes/_stream_.dataandmoneystream.html
Compared to
> feat: update documentation them to typedoc-neo-theme

- package-lock.json
- package.json
- src/connection.ts
- src/crypto.ts
- src/index.ts
- src/pool.ts
- src/server.ts
- test/connection.test.ts
- test/index.test.ts
- test/mocks/plugin.ts
Improvements:
- **Safely closing the server.** Waits for all incoming ILP Prepare packets currently being handled to be returned + 100ms before disconnecting the plugin and resolving `Server.close()`. Also added a test that attempts to create this race condition.
- **Callback/custom logic before fulfilling packets.** Enables a `shouldFulfill` callback function to be passed to the connection or server, which will be called last before fulfilling an incoming ILP Prepare with money. This enables applications to perform async operations to account for the incoming packet in their own system, and/or choose to fulfill or reject any individual packet. A couple minor questions:
- I changed `totalReceived` so it no longer throws if there's an overflow, since that's the only case where the packet …
> feat: server reliability improvements

- scripts/generate-fixtures.ts
- src/connection.ts
- src/crypto.ts
- src/index.ts
- src/packet.ts
- src/pool.ts
- src/server.ts
- src/stream.ts
- src/util/crypto-browser.ts
- src/util/crypto-node.ts
- src/util/receipt.ts
- test/connection.test.ts
- test/crypto.test.ts
- test/fixtures/packets.json
- test/index.test.ts
- test/mocha.opts
- test/packet.test.ts
- test/util/receipt.test.ts
https://github.com/interledger/rfcs/issues/568
Depends on https://github.com/interledger/rfcs/pull/570
Implementation details include:
- the server encodes the receipt nonce and secret (from SPSP queries) and appends them together as an additional segment after the token/connection tag in the destination address
- the latest receipt is exposed to the sender on the stream object allowing them to get it with every `outgoing_money` event and/or after calling `sendTotal`
> feat: add receipts

- src/connection.ts
- test/connection.test.ts
- Fix server hanging on shutdown if client never shared their ILP address
- Share asset details in response to every `ConnectionNewAddress` frame
- Fix bug in `totalReceived` accounting in `StreamMaxMoney` frames
> Minor fixes for send-only clients

- .gitignore
- src/index.ts
- src/util/receipt.ts
- test/util/receipt.test.ts
re: https://github.com/interledgerjs/ilp-protocol-stream/issues/144
> feat: accept secret generator for verifyReceipt

- src/pool.ts
- src/util/aging-set.ts
- test/util/aging-set.test.ts
To avoid leaking memory, don't store the connection Ids of closed connections indefinitely. Storing them for 20 minutes should be plenty.
> perf(server): clean up closed connections

- src/connection.ts
Fixes a bug that Uphold ran into. An uncaught rejection was bubbling up from `end()`.
I was unable to reproduce locally or as a test case. My best guess is that the error is triggered by a concurrent `startSendLoop` (i.e. the exchange rate probe) that triggers an error event, while simultaneously a `ConnectionClose` frame is being handled. The `error` is caught by the `.once('error', reject)` in the `end` method, which bubbles it up.
Also includes a fix for an unrelated `sendData` error.
> fix uncaught rejection
